export const orangeCounties = [
  "Alba County",
  "Arad County",
  "Argeș County",
  "Bihor County",
  "Bistrița-Năsăud County",
  "Brașov County",
  "Caraș-Severin County",
  "Covasna County",
  "Dolj County",
  "Gorj County",
  "Harghita County",
  "Hunedoara County",
  "Ialomița County",
  "Iași County",
  "Maramureș County",
  "Mehedinți County",
  "Mureș County",
  "Olt County",
  "Vâlcea County",
  "Satu Mare County",
  "Sălaj County",
  "Sibiu County",
  "Suceava County",
  "Teleorman County",
  "Timiș County",
  "Cluj County",
  "Giurgiu County",
] as const;

export const orangeCountySet = new Set<string>(orangeCounties);
