export type OrangeServicePackage = { code: string; description: string; unit: string; qafRow: number; mainPackage?: boolean };

export const orangeServicePackages: OrangeServicePackage[] = [
  { code: "FO Incident Diagnose", description: "Măsurători FO în site pentru diagnosticarea incidentului", unit: "intervenție", qafRow: 2 },
  { code: "Continuous Follow Up Infra Optical Fiber", description: "Evaluare și raportare infrastructură fibră optică", unit: "km", qafRow: 3 },
  { code: "SP1 FO", description: "Reparații în site / ODF / patch", unit: "intervenție", qafRow: 4, mainPackage: true },
  { code: "SP2 FOA", description: "Reparații aeriene fără cablu nou", unit: "intervenție", qafRow: 5, mainPackage: true },
  { code: "SP3 FOA", description: "Reparații aeriene cu sub 200 m cablu nou", unit: "intervenție", qafRow: 6, mainPackage: true },
  { code: "CR4 FOA", description: "Reparații aeriene cu peste 200 m cablu nou", unit: "intervenție", qafRow: 7, mainPackage: true },
  { code: "SP5 FOU", description: "Reparații subterane cu maximum 100 m cablu", unit: "intervenție", qafRow: 8, mainPackage: true },
  { code: "CR6 FOU", description: "Reparații subterane cu 100–300 m cablu", unit: "intervenție", qafRow: 9, mainPackage: true },
  { code: "CR7 FOU", description: "Reparații subterane cu peste 300 m cablu", unit: "intervenție", qafRow: 10, mainPackage: true },
  { code: "Directed drilling", description: "Forare orizontală dirijată", unit: "m", qafRow: 11 },
  { code: "Unguided drilling", description: "Forare orizontală nedirijată", unit: "m", qafRow: 12 },
  { code: "Pole replacement wood, composite", description: "Înlocuire stâlp lemn/compozit", unit: "buc.", qafRow: 13 },
  { code: "Pole replacement metallic, concrete", description: "Înlocuire stâlp metalic/beton", unit: "buc.", qafRow: 14 },
  { code: "Pole instalation", description: "Instalare stâlp", unit: "buc.", qafRow: 15 },
  { code: "Pole dismantling wood, composite", description: "Demontare stâlp lemn/compozit", unit: "buc.", qafRow: 16 },
  { code: "Pole dismantling metallic, concrete", description: "Demontare stâlp metalic/beton", unit: "buc.", qafRow: 17 },
  { code: "Ditch", description: "Șanț pentru instalare conducte", unit: "m", qafRow: 18 },
  { code: "Rock digging with a pneumatic hammer and hand tools", description: "Săpătură în stâncă", unit: "m³", qafRow: 19 },
  { code: "Concrete breakage", description: "Spargere beton", unit: "m³", qafRow: 20 },
  { code: "Restoration of aerian crossing type1", description: "Refacere trecere aeriană tip 1", unit: "m", qafRow: 21 },
  { code: "Restoration of aerian crossing type2", description: "Refacere trecere aeriană tip 2", unit: "m", qafRow: 22 },
  { code: "Asphalt coatings", description: "Refacere îmbrăcăminte asfaltică", unit: "m²", qafRow: 23 },
  { code: "Restoration of pavements, pedestrian alleys", description: "Refacere pavaje, trotuare și alei", unit: "m²", qafRow: 24 },
  { code: "Small civil works intervention", description: "Lucrări civile minore", unit: "intervenție", qafRow: 25 },
];
